version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx-acceptance
    restart: unless-stopped
    tty: true
    ports:
      - "82:82"
      - "445:445"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-acceptance-network

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "laravel-acceptance-app:${BUILD_NUMBER}"
    container_name: laravel-acceptance
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-acceptance-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: mysql-acceptance
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-acceptance-network

#Docker Networks
networks:
  laravel-acceptance-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
